title: Zahra Salsabila # your name (or website title) here
logo: "/images/foto_Zahra%20Salsabila%20Hernanda.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Learner. Well, thats too short, just hope its work
  <br><br>
  <a href="https://www.linkedin.com/in/zahra-salsabila-hernanda-552178201/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
